[metadata]
name = Pipeline-Sismologica-Geospaziale
version = 1.0.0

[options]
packages = find:
python_requires = >=3.9
install_requires = 
    pandas
    numpy
    obspy
    geopandas
    scikit-learn
    xgboost
    pytest
    pytest-cov
    pytest-mock

[options.packages.find]
exclude = tests*

[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
